project_id = "smkckhsvzyjttzqhpzhv"

[api]
enabled = true
port = 54321
schemas = ["public", "auth", "storage"]

[db]
port = 54322
major_version = 17

[db.migrations]
enabled = true

[auth]
enabled = true

[storage]
enabled = true

[edge_runtime]
enabled = true
