// =============================================================================
// Database TypeScript Types
// GENERATED by: supabase gen types typescript --local
// DO NOT EDIT — regenerate when schema changes
// =============================================================================
//
// Run to regenerate:
//   supabase gen types typescript --local > src/types/supabase.ts
//
// =============================================================================

// Placeholder — run the command above after migrations are applied.
// The generated types will be exported from src/types/supabase.ts
