// Generated by `npm run gen:types`
// Run after database migrations are applied to get the latest types.
// Example structure:
//
// export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
//
// export interface Database {
//   public: {
//     Tables: {
//       profiles: { Row: Profile; Insert: ProfileInsert; Update: ProfileUpdate };
//       wallets: { Row: Wallet; Insert: WalletInsert; Update: WalletUpdate };
//       // ... all 19 tables
//     };
//     Views: {};
//     Functions: {};
//     Enums: {};
//   };
// }

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: Record<string, {
      Row: Record<string, Json>;
      Insert: Record<string, Json>;
      Update: Record<string, Json>;
    }>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
