// Generated by `npm run gen:types`
// Run after database migrations are applied to get the latest types.
// Example structure:
//
// export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
//
// export interface Database {
//   public: {
//     Tables: {
//       profiles: { Row: Profile; Insert: ProfileInsert; Update: ProfileUpdate };
//       wallets: { Row: Wallet; Insert: WalletInsert; Update: WalletUpdate };
//       // ... all 19 tables
//     };
//     Views: {};
//     Functions: {};
//     Enums: {};
//   };
// }

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      card_orders: { Row: any; Insert: any; Update: any };
      card_products: { Row: any; Insert: any; Update: any };
      notifications: { Row: any; Insert: any; Update: any };
      payment_transactions: { Row: any; Insert: any; Update: any };
      profiles: { Row: any; Insert: any; Update: any };
      supported_networks: { Row: any; Insert: any; Update: any };
      supported_tokens: { Row: any; Insert: any; Update: any };
      supported_wallet_addresses: { Row: any; Insert: any; Update: any };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
