name: Release
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  tag:
    if: github.event.head_commit.message != 'chore: release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
